### ISSUE TITLE
EditorErrors: Warning: No assets to check in! (2.11, 2.12-beta)

### ISSUE THREAD

**Issue by CodeFunction** [SRombauts/UE4GitPlugin#104]
When first setting up the plugin, it makes the initial commit on initializing.

After that repeated push uses say successful but cannot check out / commit anything new.

When using Submit to Source Control the following happens
`SourceControl: fatal: D:/Epic/UE_4.22/Engine/Content: 'D:/Epic/UE_4.22/Engine/Content' is outside repository `

And then it fails
`EditorErrors: Warning: No assets to check in!`

This is with all plugin settings in use. Also to note that VS is installed as much as possible to a second internal drive (D:).

Looks like either its because VS is split on two drives and/or because of the setting for including /Content ?

**Comment by CodeFunction** [comment]
Further test shows Content/ new uasset will allow Submit to Source Control to work and pushes correctly to Github but not any existing umap's in Content/

File view on computer shows the umap has been changed and should be able to be committed and pushed to Github.

**Comment by CodeFunction** [comment]
Fixed. Had to disable Uses git lfs2 file locking workflow.

Content/* still works after this and commit and push as well and now its allowing commit and push of existing files.

**Comment by SRombauts** [comment]
Thanks for reporting this. I am not actively using LFS anymore, so the support might be half broken, sorry.

In case you find some more bugs, please send logs and I would look into it
