### ISSUE TITLE
"The following modules are missing or built with a different engine version" on Linux UE4 4.22.1 built from source

### ISSUE THREAD

**Issue by NazzarenoGiannelli** [SRombauts/UE4GitPlugin#105]
I've compiled UE4 from source and everything works fine here on my Linux laptop. It looks like UE4GitPlugin does not recognize my "home made" engine version as a regular 4.22.1 and I get the "The following modules are missing or built with a different engine version" popup when launching the project. As always the following popup asking to rebuild the project in order to fix the issue cannot really fix it.
Any suggestion on how to solve this?
Thanks :)

**Comment by chozabu** [comment]
It may be worth trying to put the plugin in your main UE4 source engine/plugins directory - then compiling ue4, and it will hopefully compile the plugin, making it accessable to various projects. I've had this work for other plugins under linux

Also Hi Nazzareno, we have met before :) (I am not developer of this plugin, just hanging around)

**Comment by SRombauts** [comment]
I've not tried to compile the plugin under Linux recently...

Note that if you try to put the Git V2 plugin in Engine folder, you will have a conflict with the integrated git plugin v1

See: Global namespace 'GitSourceControl' used already #94

You can always delete the original Git SourceControl v1 to let the v2 take control. 

Let us know how it goes

**Comment by NazzarenoGiannelli** [comment]
> It may be worth trying to put the plugin in your main UE4 source engine/plugins directory - then compiling ue4, and it will hopefully compile the plugin, making it accessable to various projects. I've had this work for other plugins under linux
> 
> Also Hi Nazzareno, we have met before :) (I am not developer of this plugin, just hanging around)

Hey Alex! How are you? That's crazy to hear back from you on GitHub XD

That said...I copied the plugin in the plugins engine folder, but nothing changed. What do you mean with "compiling ue4" after copying the plugin in the engine/plugins folder? I still have to learn many things about Git...I was able to compile the engine from source, but maybe I am missing something on how a source built version of the engine works.

**Comment by TotallyCoded** [comment]
Try copying the whole plugin folder and not just the .uplugin. I got that same error when only copying the .uplugin but after copying the whole folder it seems to have worked.

**Comment by hcorion** [comment]
Just FYI for those facing the same issue, I was able to succesfully compile by following this tutorial and building manually using `RunUAT.sh`: <https://www.youtube.com/watch?v=WtfLfYY_k2Y>

**Comment by SRombauts** [comment]
For future reference, it writen quite clearly in the README for some time now:

```
Install this Git Plugin (dev) into your Game Project
Unreal Engine comes with a stable version of this plugin, so no need to install it.

This alternate "Git development plugin" needs to be installed into a subfolder or your Game Project "Plugins" directory (that is, you cannot install it into the Engine Plugins directory):

<YourGameProject>/Plugins
You will obviously only be able to use the plugin within this project.
```

If anyone would like to suggests improvements to the docs, please do :)

Cheers!
Sébastien
