### ISSUE TITLE
Problem with local only branches

### ISSUE THREAD

**Issue by adnoh** [SRombauts/UE4GitPlugin#107]
I tried to active git-lfs plugin in ue for my already working git repo. I'm on a local development branch which is (and should not) be pushed to the server.
Activating fails because of line:
https://github.com/SRombauts/UE4GitPlugin/blob/310040f3a03f3f5a30c86b729830a4719d23f3d8/Source/GitSourceControl/Private/GitSourceControlUtils.cpp#L1081
I don't know why you are adding origin here ...
From the logs:
LogSourceControl: RunCommand: 'git diff --name-only origin/MyBranchName  HEAD "F:/ull/Path/To/Project/Content"'
LogSourceControl: RunCommand(diff):
LogSourceControl: Warning: RunCommand(diff) ReturnCode=128:
fatal: ambiguous argument 'origin/MyBranchName': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by mateosss** [comment]
Can confirm, would be nice to have it working with local only branches as well.

**Comment by SRombauts** [comment]
Thank you for reporting this issue, it has been fixed and I will release an update soon.
