### ISSUE TITLE
BE CAREFUL, plugin is outdated

### ISSUE THREAD

**Issue by ERCryptX** [SRombauts/UE4GitPlugin#111]
Looks like this plugin does not work with 4.22 anymore. Checking out does not work anymore and the plugin deletes files for some reason (my .gitignore has been deleted when trying to check out an asset).

Just to warn you guys

**Comment by SRombauts** [comment]
Sorry, I checked again and it is working as expected.

You may have hit a specific or random bug, can you provide some log, please?
