### ISSUE TITLE
Unable to build the plugin. "FApp is not a class or namespace name"

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [SRombauts/UE4GitPlugin#117]
When downloading the newest version from releases tab, (2.13-beta), and I copy that to my plugins folder, unreal asks me to rebuild the plugin. When I press yes, it starts to build, but fails with the message "`MyProject could not be compiled. Try rebuilding from source manually`"

Looking at the log when building I see the current errors showing up:

```
C:\myProject\Pluigns\UE4GitPlugin\Source\GitSourceControl\Private\SGitSourceControlSettings.cpp(50): error C2653: 'FApp': is not a class or namespace name
C:\myProject\Pluigns\UE4GitPlugin\Source\GitSourceControl\Private\SGitSourceControlSettings.cpp(50): error C3861 'GetProjectName': identifier not found
```

I have tried a bunch of things, like updating my Visual Studio dependencies, verifying unreal engine etc. Tried building on another computer as well, but same results.

Running on version 4.23.1 of Unreal Engine on windows 10

Is there something I am missing, or could this be a bug?

**Comment by SRombauts** [comment]
Hello, I'll have to have a look at the release since you should not have to rebuild the plugin!
About missing FApp, it's even weirder but I might be able to reproduce it if it's relative to the first problem above

**Comment by varthshenon** [comment]
I'm getting the mssage as well
"... could not be compiled. Try rebuilding from source manually"

**Comment by SRombauts** [comment]
Sorry but I have just tried it one more time, using UE4.23.1 binary from the Unreal Launcher and a source zip download from my latest 2.13-beta release (unzipped in a new Plugins folder in my project) and it's working like a charm for me.

Tested with a fresh new third person BP project. Would you be able to retest with such a test project? 

Anything else tha

**Comment by varthshenon** [comment]
Tried on blank Third Person BP Project. Still getting the same message

**Comment by SRombauts** [comment]
Okay, I think there are two different problems here:

1. @stephan-nordnes-eriksen did probably not pick the last release for Windows, so the Engine ask him to rebuild the plugin, which never happens with an official release for which I provided Binaries for Win64
2. @varthshenon is on Mac, so in this case it is normal that you have to rebuild
3. The rebuild itself should not fail (I just forced a rebuild on my template project and it went fine) 

=> for the rebuild issue I will see what include is missing, since the most obvious problem in my opinion is a "non unity build" issue where includes are missing but not causing issue for "unity builds"

**Comment by SRombauts** [comment]
Adding `bFasterWithoutUnity = true;` to UE4GitPlugin\Source\GitSourceControl\GitSourceControl.Build.cs enabled me to reproduce and fix the compilation issue.

Thanks for reporting this.

Cheers!

**Comment by stephan-nordnes-eriksen** [comment]
@SRombauts I will try your suggestion as soon as possible. I have some other pressing matters to take care of first. I will keep you posted.

Regarding your feedback. I am pretty sure I downloaded the correct release for windows, but just in case, could you link to it so that I am sure I am not messing it up?

**Comment by SRombauts** [comment]
I meant, downloading the "source code" zip or gzip from https://github.com/SRombauts/UE4GitPlugin/releases/tag/2.13-beta (that is, the archive https://github.com/SRombauts/UE4GitPlugin/archive/2.13-beta.zip for instance)

**Comment by stephan-nordnes-eriksen** [comment]
I got it to work now!

The problem was that I work on a project with more people, and someone else had opened the project with 4.22 which caused problems. Resetting the "engine version", and getting a clean download of the plugin worked. I did not have to rebuild the binaries! :) Ps. I used 2.14-beta.

Thanks for the help!

**Comment by SRombauts** [comment]
Good, thanks for the update.
