### ISSUE TITLE
Why exactly is UE4Editor-GitSourceControl.dll added to source control?

### ISSUE THREAD

**Issue by ArosPrince** [SRombauts/UE4GitPlugin#119]
Hello,
I am not sure if this is the right place to ask about it (creating a github issue and all), but I just noticed that the two following files from the binaries folder are also added to the source control:

UE4Editor.modules
UE4Editor-GitSourceControl.dll

Why exactly is that? Is the intention so that the user may use the plugin without having to have Visual Studio installed on the machine? If so, is this really enough? I thought that it wouldn't work without the intermediate folder as well.

Thanks
Jan

**Comment by ccarvalheiro** [comment]
Hey Jan,

As far as I know, you are correct. And it should be enough, intermediate folder is always safe to be left out of source control.
Upon release, the plugin is compiled with the build configuration "Development Editor" and the binaries are added to source control. This way people working with Blueprint only projects can just drag and drop it into their Plugins folder inside the project and are ready to go.

Hope it helps
Cheers

**Comment by SRombauts** [comment]
Hello, thanks for asking, and thanks for answering ; thé point is to use the plugin in data-only projects, and I test it to be sure it works properly as intended.

Cheers !
