### ISSUE TITLE
Cannot Compile C++ Project in UnrealEngine 4.24.2 with the Plugin installed

### ISSUE THREAD

**Issue by IgnacioMGarrido** [SRombauts/UE4GitPlugin#122]
GitSourceControlProvider.cpp(22): fatal error C1083: Cannot open include file: 'IPluginManager.h': No such file or directory LogMainFrame: MainFrame: Module compiling took 66.394 seconds

**Comment by freezernick** [comment]
Try it with 
```cpp
#include "Interfaces/IPluginManager.h"
```

**Comment by ccarvalheiro** [comment]
Got the same problem today when upgrading, it fails after switching the DefaultBuildSettings to BuildSettingsVersion.V2 in older projects or new projects where that is the default already.

I opened a pull request #123 with the fix.

**Comment by watermelon-xi** [comment]
> 试试看
> 
> ```c++
> #包括 “接口/IPluginManager.h ”
> ```

thank you,but I have another question. How did you find this address.can you teach me.pleasse

**Comment by freezernick** [comment]
> 
> 
> > 试试看
> > ```c++
> > #包括 “接口/IPluginManager.h ”
> > ```
> 
> thank you,but I have another question. How did you find this address.can you teach me.pleasse

You can use the [API Documentation of the Unreal Engine](https://www.unrealengine.com/en-US/bing-search?keyword=IPluginManager&offset=0&filter=UE4%20C%2B%2B%20API) to look for specific classes, functions etc.

When you are on a page of a class, you'll find the Include Path / Statement listed there.

E.g: https://docs.unrealengine.com/4.27/en-US/API/Runtime/Projects/Interfaces/IPluginManager/
