### ISSUE TITLE
IPluginManager not found (does not compile)

### ISSUE THREAD

**Issue by narthur157** [SRombauts/UE4GitPlugin#126]
In `GitSourceControlProvider.cpp` I had to change the include for `"IPluginManager.h"` to `Interfaces/IPluginManager.h`, in order to compile in 4.24 (2.15-beta).

I tried to make a PR, however there's no .uproject to generate the .sln files. Maybe you're supposed to be able to do that with the .uplugin file?

**Comment by freezernick** [comment]
This has already been fixed with ef9b0d9676f23499136e8cdb1b06cc115e9437db
