### ISSUE TITLE
Blueprint merge image is broken

### ISSUE THREAD

**Issue by guitarjorge24** [SRombauts/UE4GitPlugin#141]
The image in the home page that is supposed to show the blueprint merge feature is broken. It shows up like this: 

![image](https://user-images.githubusercontent.com/12472021/84606468-732d2800-ae74-11ea-9526-31284b80a134.png)

**Comment by SRombauts** [comment]
Thanks, see fix #151 README & .io Site missing the Blueprint Merging Image

Epic Games modified their Blueprint merge image
