### ISSUE TITLE
Authentication is not managed if needed for Sync (Pull)

### ISSUE THREAD

**Issue by dskvr** [SRombauts/UE4GitPlugin#144]
For anyone who's interested, I was able to completely bypass this problem by using ssh keys. Just make sure you use an `ssh` style git reference instead of an `https` style reference when configuring your project. 

## Instructions
1. [Setup SSH keys](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
2. Example SSH reference: `git@github.com:SRombauts/UE4GitPlugin.git` (on Github, click "ssh" after clicking "code") 

I already had SSH keys configured on my systems and almost exclusively use SSH for git. So when a colleague was unable to authenticate, we went through some troubleshooting steps and I setup SSH keys on his system and it worked. That said, we were still have all kinds of random issues, so it may not resolve everything. We are using this plugin primarily for diffs since LFS Locks was causing all kinds of problems. Way easier to just `git lfs lock` than to spend 30 minutes trying to tinker with a gui.

**Comment by SRombauts** [comment]
Thanks for documentating this :)
