### ISSUE TITLE
README & .io Site missing the Blueprint Merging Image

### ISSUE THREAD

**Issue by SlaggyWolfie** [SRombauts/UE4GitPlugin#151]
This is not a major issue. Just wanted to point it.

~~Don't crucify me.~~

![image](https://user-images.githubusercontent.com/2999718/99272842-f17d6400-2830-11eb-9176-92e7cb137088.png)

**Comment by SRombauts** [comment]
Hello @SlaggyWolfie thanks for reporting :)
