### ISSUE TITLE
Update for 4.26

### ISSUE THREAD

**Issue by brybalicious** [SRombauts/UE4GitPlugin#154]
Hi,

Any updates planned for 4.26? Or will it work just to rebuild the plugin for 4.26 manually?

Thanks

**Comment by SRombauts** [comment]
Hi @brybalicious

Thanks for asking, I am doing this right now, and have already pushed updated binaries for 4.26 :)

**Comment by SRombauts** [comment]
https://github.com/SRombauts/UE4GitPlugin/releases/tag/2.17-beta
