### ISSUE TITLE
UE4 Plugin Unable To Handle Umlaut U

### ISSUE THREAD

**Issue by jgthompson90** [SRombauts/UE4GitPlugin#160]
One of my assets was spelled using an umlaut U, 
![image](https://user-images.githubusercontent.com/41306212/113601119-d7ee8480-9638-11eb-8ae0-6ae76cdeeddf.png)

I received the following error:

![image](https://user-images.githubusercontent.com/41306212/113601245-fce2f780-9638-11eb-91d3-769c9380d41b.png)
(ignore the DefaultCrypto, that error went away) 

So the Plugin couldn't handle that character and changed it to a "?". It would not let me sync or update the workspace. I couldn't Checkin any changes. It made me unable to do anything using PlasticSCM. I tried to change the name of the asset in the PlasticSCM storage and locally in the workspace. That didn't work. I tried to make a new branch, that didn't work. Nothing was working. 

This error only occurs in the Plugin. The GUI and CLI doesn't have this issue and could handle the umlaut U and other characters. 

I copied the files in my content folder, with the renamed asset using an English U and I ended up having to revert to a previous controlled version before I checked in that asset. I copied in the files directly to the repository and checked them in using the GUI. Once I did that I was able to regain use of PlasticSCM within my workspace.

**Comment by RumbleballTheReal** [comment]
Never ever use anything else then "a-zA-Z0-9_" and "-" for file names, ever.

**Comment by SRombauts** [comment]
Woups, this if for my other plugin https://github.com/SRombauts/UE4PlastcPlugin
