### ISSUE TITLE
UE5 Support

### ISSUE THREAD

**Issue by martysmind** [SRombauts/UE4GitPlugin#174]
Does/WIll this support UE5?

**Comment by SRombauts** [comment]
Hey @martysmind, thanks for asking!
Yes I have been working on this in the background, starting to investigate a few months ago...
I did submit & push an [unreal-5-support](https://github.com/SRombauts/UE4GitPlugin/tree/unreal-5-support) a couple of weeks ago
It's now tracked by #175 Unreal Engine 5 support, so it's public and reviewable

Feel free to have a go at it, it seems working for me so I should merge it soon with some time to test it

**Comment by martenzander** [comment]
are there any precompiled versions for 5.5 or 5.6 somewhere? :)
