### ISSUE TITLE
 Unable to use on mac

### ISSUE THREAD

**Issue by LoeizD** [SRombauts/UE4GitPlugin#23]
I followed the setup guide, I use the github visual client. When I launch unreal I get the following messages:

![capture d ecran 2015-02-28 a 13 03 36](https://cloud.githubusercontent.com/assets/8215178/6426185/9c24a726-bf4e-11e4-84e1-93fa8502dfd9.png)

**Comment by SRombauts** [comment]
Yes, as stated in the Know Issues list of the README, the plugin is "Windows only (64 bits) -> Mac compiles but needs testing/debugging (Linux source control is not supported by Editor)" 

This is because I have no access to a Mac, sorry! 

If you are willing to help, we could add more debug logs to your copy of the plugin to try fix this

**Comment by LoeizD** [comment]
I don't know much about git, but if you tell me what to do I sure can help.

**Comment by tgunr** [comment]
Who created the UE4Editor-GitSourceControl.dylib for Mac that is distributed with the 4.7 engine. I am a Mac developer and we are planning on using Unreal and having a GIT plugin is a must.

**Comment by SRombauts** [comment]
Epic did, and perhaps the Git plugin was tested successfully on certain
configuration, but does not handle well certain paths (like spaces on the
path to the project) or other things they did not yet.

**Comment by SRombauts** [comment]
Today I had a chance to test the Git plugin with a Mac, and unfortunately it does not work at all, whether there is a space or not in the path to the Project.

The problem come from the double-quotes added around path to handle space (like "/Users/Xxx/Unreal Projects/TestGit") : those does not work with the current UE4 FPlatformProcess::ExecProcess() method on Mac.

I've try with simple-quote instead, but this does not work either.

I've try removing them altogether, and this works if you don't have any space in any of your paths.

I'll report this to Epic, as I have no way to work seriously on resolving this issue.

**Comment by SRombauts** [comment]
Fixed on the Unreal Engine master branch with my pull request:
https://github.com/EpicGames/UnrealEngine/commit/2196a60dd6e5e59576a0e6ade6c3a4b621b4fe86
