### ISSUE TITLE
Crash on Blueprint merge during conflict?

### ISSUE THREAD

**Issue by abhisheksagi** [SRombauts/UE4GitPlugin#24]
Hello,

Currently when there is a merge conflict between 2 blueprint files and if I select "Merge" under source control option engine crashes. Is this something your aware of? 

Thanks :)

**Comment by abhisheksagi** [comment]
Ignore my post, I came across this http://srombauts.github.io/UE4GitPlugin/ where you mentioned that your working on it for V1.0 release. Closing this issue.

**Comment by SRombauts** [comment]
Ok, problem found, I need to work on this soon 
https://answers.unrealengine.com/questions/181563/471-crash-blueprint-merge-tool-crashes-editor.html?sort=oldest

**Comment by SRombauts** [comment]
I finally made a pull request to enable 'Blueprint Merge' with the Git plugin: https://github.com/EpicGames/UnrealEngine/pull/1043

**Comment by SRombauts** [comment]
This has been merged in UnrealEngine master for the upcoming UE4.8 release, so closing the issue
