### ISSUE TITLE
Instructions for using git-annex, git-lfs under Windows

### ISSUE THREAD

**Issue by fire** [SRombauts/UE4GitPlugin#27]
Is it possible to have instructions using gitlab.com git-lfs and git-annex?

**Comment by SRombauts** [comment]
Hi, yes I should add a short tutorial in the readme. 

I've made a small test project (https://github.com/SRombauts/UE4GitLfsTest)  using https://git-lfs.github.com/

As a quick start, in your UE4 project :
- git lfs install
- git lfs track *.uasset
- git add .gitattributes
- git commit .gitattributes
Then every uasset files (Blueprint, Materials...) can be added and commited as usual through the Editor. 

I will add explicit git lfs support to the plugin to ease this step to init a new repository

**Comment by fire** [comment]
How do you approach storing the Unreal Engine deps in lfs?

**Comment by SRombauts** [comment]
Oh, I see... sorry but I do not fork the Engine to the point I fork it's dependencies, so I have no idea.

**Comment by fire** [comment]
It would be great if you could find out. Having a viable alternative to perforce will be great.

**Comment by fire** [comment]
Will create a new issue on importing a complete ue4 directory. The basics work though.
