### ISSUE TITLE
List of default binaries files for GIT-LFS

### ISSUE THREAD

**Issue by fire** [SRombauts/UE4GitPlugin#28]
Is there a predefined list of GIT-LFS files for UE4 projects that are binaries?

Stuff like:
- .uasset
- .mp4
- ETC

Maybe if the file is bigger than 300 KB it'll prompt to add it to LFS.

**Comment by SRombauts** [comment]
Not that I am aware of, but will probably work on this sometime later

**Comment by SRombauts** [comment]
I will try to work on this if I can get Git LFS to work correctly (issue #35)

**Comment by SRombauts** [comment]
Default ".gitattributes" file will contain just one line:

```
Content/** filter=lfs diff=lfs merge=lfs -text -lockable
```

The "lockable" part is new to [Git LFS 2.0.0 (see #36)](https://github.com/SRombauts/UE4GitPlugin/issues/36) but is retro-compatible with LFS 1.x (tested with Git LFS 1.5.5)

**Comment by BenjaminDSmithy** [comment]
@fire @SRombauts I'm working on a new UE4 Git LFS Template project which I'll be uploading to GitHub once it's better defined but if you'd like to check out the earlier revisions please see: https://bitbucket.org/BinarySword/ue4-git-template/src

Just note that I will probably not be accepting any Pullback requests on Bitbucket Cloud, so you'll either have to wait until it's uploaded to GitHub or message me directly with your suggestions.
