### ISSUE TITLE
changing branch - no option to check out in editor

### ISSUE THREAD

**Issue by LarsGroh** [SRombauts/UE4GitPlugin#30]
Hi, 

I postet this post in Unreal Answer Hub a while ago. Unfortunately there was no response.
Can you helpt me with this:

When I switch the branch of my repo (in my git console), the Unreal editor does not give me the option to check out changed files. The files change on disk, but the editor does not seem "to notice" that they were changed.

Do I have to restart the editor whenever a file (e.g. a blueprint) is changed on the file system (either by pulling from a remote or switching to a branch, which holds changes)? Or ist there any other way to force the editor to check out the changed version - the context menu on the respective asset does not give me this choice either!

**Comment by SRombauts** [comment]
Hi @LarsGroh, sorry the lack of answer, can you post the link to your Answer Hub post please ?

But basically, yes you have to relaunch the Editor when you change something on disk, unless it's only an image source of a texture.

Cheers!

**Comment by LarsGroh** [comment]
Hi @SRombauts, 

thanks for your answer. Then I know what kind of drawbacks I have to deal with for now. But I guess we can still use Git for production - restarting the editor won't be necessary too often.

Just one thought: wouldn't it be possible for the plugin to query the repo for changed files of the last commit and then update the asset within the editor?

Here ist my AnswerHub Post:
https://answers.unrealengine.com/questions/474479/git-changing-branch-no-option-to-check-out-in-edit.html#answer-484557

**Comment by SRombauts** [comment]
No, sorry, this feature would have to be in the Editor itself: the plugin has only some limited powers.
