### ISSUE TITLE
Issue related to saving checked in assets.

### ISSUE THREAD

**Issue by Matthew-Clark** [SRombauts/UE4GitPlugin#31]
Hello SRombauts,

Thanks to the report of a user, we came across an issue where saving an asset that is currently checked in will cause it to be checked out immediately without any confirmation. This isn't exactly a bug but causes issues with workflow so you can see this as more of a feature request. The favorable behavior would mimic the Perforce plugin where it asks if you would like to check out the asset, make it writable, or cancel the process. I put a bug report in for the issue and made it public so you can track it [here](https://issues.unrealengine.com/issue/UE-36027)

You can see a picture of what the Perforce behavior looks like on the Answerhub post that is linked to that bug report.

Thank you for your time!

**Comment by SRombauts** [comment]
Hi @Matthew-Clark, I am not totally sure on how and if I could trick Git on working with a "checkout" operation it does not know about. So in the Git plugin, every files are always said "checked-out".

But there IS a change introduced on one previous version of the Engine that broke the way the Git plugin is working: previously, you where not abled to checkin a file when the plugin returned CanCheckout()==false
=> now those unchanged files are displayed in the checkin window, which is a mess...

**Comment by Matthew-Clark** [comment]
Ah, I'm not all that familiar with using Github's source control myself so I'm not completely aware of how it handles the checking out and such. As I mentioned to the user, if a checkout-type system isn't possible, would it be possible to add a confirmation window of sorts when saving while connected to Github source control? Even if this is an optional thing and isn't on by default, it would be helpful for the user's case.

I'm going to go ahead and change the JIRA report to a Feature Request.

**Comment by SRombauts** [comment]
Yes it's entirely possible, even easy to fake the 'checkout' workflow.

It should be optionnal, but it could becomes the default.

Do you have a time frame ? Could it make it into 4.14 or is it already too late?

**Comment by Matthew-Clark** [comment]
I can't give any exact deadlines but it would be best if you could get it in within a couple of weeks.

**Comment by SRombauts** [comment]
This is fixed by supporting Git LFS 2 File Locks in v2.3 of the plugin #36
