### ISSUE TITLE
git-annex on windows?

### ISSUE THREAD

**Issue by rpav** [SRombauts/UE4GitPlugin#33]
Is git-annex actually supported on Windows?  I've tried setting it up via `annex.largefiles` settings and this works when using `git annex add ...` from the commandline, but adding/committing via the editor's menu seems to bypass this and still commits directly to git (surprisingly since git-annex normally disables `git-add` etc for direct mode).

**Comment by SRombauts** [comment]
No, I am sorry, neither git annex nor git fat are supported. And Git LFS support is broken (no diff, see issue #35).
