### ISSUE TITLE
[Git LGS] Unable to load assets to diff. Content may no longer be supported?

### ISSUE THREAD

**Issue by FredyC** [SRombauts/UE4GitPlugin#35]
I started using the plugin on a small project, but I seem to unable make a diff working. I am using LFS for all `*.uasset` and `*.umap` files since start of the project, but that should be working as per readme, right?

I am on Windows 10 x64.
git version 2.10.1.windows.1
git-lfs/1.5.2 (GitHub; windows amd64; go 1.7.3; git 547a06aa)

**Comment by SRombauts** [comment]
Hi, yes I was able to make it work, but it was on an old Engine version. Which one are you using ? Is it a binary version from the launcher ? 

I will try to have a look at it, but not today as don't have my computer with me.

**Comment by FredyC** [comment]
Yes, I am using latest UE 4.14.1 from the launcher.

**Comment by SRombauts** [comment]
Hi @FredyC, I did reproduce the problem, and looking into it I am not sure it has ever worked.

I will try to work into it soon, but I cannot promise that when it would get integrated into UE.

Sorry about that!

**Comment by FredyC** [comment]
@SRombauts Thanks, at least there is a hope for brighter future :)

**Comment by SRombauts** [comment]
Also, it appears that this problem [has already been reported in AnswerHub (Git LFS Diff not working](https://answers.unrealengine.com/questions/466658/git-lfs-diff-not-working.html) and is officially tracked as [issue UE-34539 in Epic Games JIRA](https://issues.unrealengine.com/issue/UE-34539)

**Comment by rpav** [comment]
I actually recently submitted EpicGames/UnrealEngine#3057 which solves this as well.

**Comment by SRombauts** [comment]
Hi @rpav, this is a really good news, and perfectly on time!
I'll check what you submitted asap, and will report here and on the Merge Request itself.
Cheers!

**Comment by SRombauts** [comment]
Your solution is working and elegant!
I hope we could get it in quickly.

**Comment by SRombauts** [comment]
@rpav, I have added [a commit on my git-plugin-smudge-diffs branch](https://github.com/SRombauts/UnrealEngine/tree/git-plugin-smudge-diffs) with some small improvements:

* Delete the temp dir after the checked-out file has been moved
* And do not create this temp when the file has already been checked-out previously

Could you cherry-pick this onto your merge request branch please?

**Comment by SRombauts** [comment]
Thank you very much for your work, I've also referenced your Pull Request in the AnswerHub bug report [Git LFS Diff not working](https://answers.unrealengine.com/questions/466658/git-lfs-diff-not-working.html#answer-541928).

Let's hope for a quick integration in the Engine. UE4.15 would have been nice, but it's probably already too late...

I'll close this issue only when it will be integrated.

Cheers!

**Comment by FredyC** [comment]
Thank you both for actively handling this. Looking forward for this to be at least integrated into a master branch. Do I actually need something else to make it working or just to build the UE from the source?

**Comment by SRombauts** [comment]
You only have to build from source, nothing else.

**Comment by SRombauts** [comment]
The topic is not closed, I found an issue with the solution, and rpav had to rethink it into a new pull-request EpicGames/UnrealEngine#3253 which will work only with latest git 2.11 (29 nov. 2016)

**Comment by SRombauts** [comment]
Merge 3 days ago in Epic Games master, in time for UE4.16
