### ISSUE TITLE
UE4.16 compatibility problem

### ISSUE THREAD

**Issue by rkorovin** [SRombauts/UE4GitPlugin#43]
I clone as submodule your master but it don't work. Editor write "plugin's compatibility error" (verb.) and shuttin down. On 4.15 it worked well.

**Comment by SRombauts** [comment]
Hi @rkorovin, it's my fault, I wanted to try fixing every know issues before making a release for UE4.16, and endded not having the time to work on this.

So here I've just pushed a new release for the plugin "as-is" for UE4.16.

Cheers!

**Comment by rkorovin** [comment]
Thanks!) Now I'll check...
