### ISSUE TITLE
Git LFS not working on Mac

### ISSUE THREAD

**Issue by SRombauts** [SRombauts/UE4GitPlugin#50]
First report of this issue in Mars 2017:

> First of all, thanks for providing the Unreal Engine 4 git plug in. I'm a mac user and I have installed git and git lfs successfully in my computer. I have already created a new repository and I'm using Unreal and git to work with another partner. Everything that is not LFS can be checked-in form Unreal without issues. However, everything LFS can't be checked-in, and every time I try to check-in any LFS file from Unreal I get the following errors:
```
Error git-lfs filter-process: git-lfs: command not found
Error fatal: The remote end hung up unexpectedly.
```
> 
> Do you know if there is a workaround to this issue? Maybe I'm still missing an additional step when installing git. 
> 
> As additional information, I can manually sync LFS files directly from Github, but as mentioned before, not from Unreal.

**Comment by SRombauts** [comment]
Same issue raised [on AnswerHub: Git-LFS problems on MAC on 2017/09/09](https://answers.unrealengine.com/questions/704810/git-lfs-problems-on-mac.html )

**Comment by SRombauts** [comment]
As mentioned before, I don't have a Mac and have no access to one.

I should try to see if there is the same issue under Linux to try to solve it here first.

**Comment by shiena** [comment]
@SRombauts I posted a PR to UnrealEngine to fix it.
https://github.com/EpicGames/UnrealEngine/pull/4231

You can solve it by applying the following script to Git Path.
(e.g. the path of git-lfs installed by homebrew)

```
#!/bin/env
env PATH=/usr/local/bin:$PATH /usr/local/bin/git "$@"
```

**Comment by SRombauts** [comment]
Ah, nice!

**Comment by shiena** [comment]
@SRombauts  I added a comment to PR so please check it.

**Comment by appcornerdev** [comment]
Hi!
Have the same error bud i don't now how to applying the script above :o(
Any instruction how i can do that?
Thanks

**Comment by shiena** [comment]
@appcornerdev I answered to same issue on answerhub.
Please see https://answers.unrealengine.com/questions/704810/git-lfs-problems-on-mac.html

**Comment by appcornerdev** [comment]
@shiena Tanks alot, it works now :o)

**Comment by FlynnRingrose** [comment]
Hi SRombauts,

I'm currently trying to decide between using Git LFS 2 or Perforce for my Unreal Projects with a team of four. Some of us use Macs and others are on Windows.

Is Git LFS 2 a viable option in Unreal on a Mac yet or will this still be a long time coming?

Thanks for all your hard work.

**Comment by SRombauts** [comment]
Hi all, it's a bit sad to see that this as only been merged a few days ago, but it's still a good new!
- https://github.com/EpicGames/UnrealEngine/pull/4215
- https://github.com/EpicGames/UnrealEngine/pull/4231
