### ISSUE TITLE
Locking/Unlocking multiple files with Git LFS 2

### ISSUE THREAD

**Issue by ALPHAKENT** [SRombauts/UE4GitPlugin#56]
When u try to check in more than 1 asset, only the first one unlocks. Others remain "check outed", and u need revert, to get reed of it.

**Comment by SRombauts** [comment]
Oh, nice catch, should be easy to fix

**Comment by SRombauts** [comment]
I've submitted a fix, it works now for me :)

**Comment by ALPHAKENT** [comment]
Nice. By the way, is it possible to make pushing to server without stunnig editor in a small window? Even better with status bar. It would save a couple of minutes while updating several files or a large one like .umap so i can use editor same time.

**Comment by SRombauts** [comment]
No it is not, it seems to me that it is "by design" in Unreal Editor, even if it does not sounds nice!
