### ISSUE TITLE
Locking asset bug

### ISSUE THREAD

**Issue by ALPHAKENT** [SRombauts/UE4GitPlugin#57]
I dont know how to reproduce this bug, but my friend tried to check out the file of my project and got error message. When he close it a blue sign appears wich say that he - “his git account name wich is not the same like in plugin setup” locked asset. So he cant edit that asset. The only way to unlock it was github desktop powershell command. We tried lot of things like reinstalling plugin, deleting save folder of project, but nothing could help.

**Comment by SRombauts** [comment]
Hi, he needs to configure his Github name on the Git Source Control settings screen.

**Comment by ALPHAKENT** [comment]
As I said he did wrote different name in source control settings screen , but locked asset says it was locked by his git web page account name

**Comment by SRombauts** [comment]
I mean, he needs to setup his Github account name and not his Git name so
that the plugin can identify his locks on the Github server
