### ISSUE TITLE
No status of updated file on the remote server ("not at HEAD" status)

### ISSUE THREAD

**Issue by ALPHAKENT** [SRombauts/UE4GitPlugin#58]
When i changed .umap asset and checked it in, my team partner wont be able to see “!” mark on asset after refreshing it. Is that function not exists, or its just a bug? And i also like to know if it possible to force refresh file on every computer automatically  after i checked it out?

**Comment by SRombauts** [comment]
1. It's a missing feature, that might not be easy to implement... 
2. Unreal Engine lock files so it is not possible (or not easy) to update files automatically

**Comment by ALPHAKENT** [comment]
That’s make this plugin not enough convinient to use. It would be easier to cooperate with team members on cloud storage services instead, and use standard auto saves and backups. Easier rather than update status of every asset before editing it and remember if it need to update or ask for update the whole project changed files.

**Comment by ALPHAKENT** [comment]
I meant auto update file statuses, not files, sorry.

**Comment by SRombauts** [comment]
Implemented by @MekuCube, assuming (for now) that you have an external tool to fetch from the remote regularly.
