### ISSUE TITLE
Plugin behavior options for add/removing files

### ISSUE THREAD

**Issue by josimard** [SRombauts/UE4GitPlugin#63]
Hi,
It would be nice if we could disable the auto-adding or auto-deleting when adding files and removing files in the content browser.

Following this scenario will often do multiple "source-control" operations that slows the process in content browser.
1. Duplicate a blueprint
2. Input name of the blueprint
3. Move blueprint to another folder

From the previous scenario, I sometimes get Git errors when "Added" files were not removed from the git index after renaming or deleting the file from windows explorer.

The following scenario will throw a "Failed to revert package which was marked for delete."
1. Delete a source-controlled blueprint with no references (which will not make a redirector)
2. Create a new blueprint with the same name

**Comment by SRombauts** [comment]
Hi @josimard, thanks for reporting this and giving all this details.

1. Edit->Editor Preferences->Loading & Saving->Source Control: uncheck **Add New Files when Modified** 👍 
2. Your second scenario seems to be a bug in the Editor itself, not in the Git plugin, though I am not sure.

**Comment by SRombauts** [comment]
I have edited my answer above for the second scenario. Please let me know if you need some more info.

And let me know if you open an issue about this with Epic Games, I am also interested to follow this.

**Comment by josimard** [comment]
Hi @SRombauts,
This editor preference sure does the trick, thanks for answering!

For the delete scenario committing will avoid the issue, and is probably a very uncommon scenario!
