### ISSUE TITLE
Not picking up User Name or Email from Git Repository

### ISSUE THREAD

**Issue by nweeden** [SRombauts/UE4GitPlugin#65]
The plugin is not automatically picking up the user name and email address from the git repo even though it has been set using git config --global.  This means it won't connect to repo at all.

**Comment by studioliddell** [comment]
Turns out my colleague had an ancient version of git (2.6), updated him to 2.16 and it all works fine now!

**Comment by SRombauts** [comment]
Ok, sorry to hear that some older version of Git are not working any more
