### ISSUE TITLE
Can't unlock files -- says locked by my user: "bunswoDS"

### ISSUE THREAD

**Issue by bunswoDS** [SRombauts/UE4GitPlugin#66]
Some of my files claim they're locked for editing by my user which is "bunswoDS" but I have no option to unlock them.  When I right click there's no option to check them in.  And if I submit to source control via the Unreal source control tab it says there is nothing to checkin.  Unreal Version 4.18.3

<img width="289" alt="locked-for-editing" src="https://user-images.githubusercontent.com/34286569/36317482-34c2f81c-130b-11e8-9254-7f1032ec8cd4.PNG">
<img width="366" alt="no-check-in" src="https://user-images.githubusercontent.com/34286569/36317483-34cf461c-130b-11e8-8bd8-51ee80b4eec5.PNG">

**Comment by bunswoDS** [comment]
(Also I downloaded the zip of the most recent version of UE4GitPlugin here on github and installed it but still have the same issue)

**Comment by SRombauts** [comment]
I'll have to check this seriously, perhaps in relation with #65

**Comment by SRombauts** [comment]
Do you have logs?

**Comment by ArtyMcLabin** [comment]
bunswoDS can you try to run "git lfs unlock" on that file from bash?

in my case the problem were that i had to add a space character or two to the end of my LFS name, and that have caused a fork between me and myself (with and without spaces)
you can view the log "window->developer tools->output log" inside Unreal Engine, and lookup the output of "git lfs locks" which shows how exactly you should write your LFS nickname in the plugin settings.

**Comment by SRombauts** [comment]
Hey @bunswoDS, I've just pushed a fix!

Would you be able to test the plugin by compiling it from source? If you need a binary release I can provide it asap.

**Comment by bunswoDS** [comment]
Thanks -- away from computer but will check with the updated files.

**Comment by SRombauts** [comment]
https://github.com/SRombauts/UE4GitPlugin/releases/tag/2.6-beta
