### ISSUE TITLE
Don't check modified files

### ISSUE THREAD

**Issue by paveldostal** [SRombauts/UE4GitPlugin#71]
Hi all,
I when modified any blueprint, materials or any content in unreal engine, plugin don`t check modified files and I have disabled "Check Out Modified Files" button

**Comment by SRombauts** [comment]
Hi @paveldostal, I am sorry but I genuinely don't know what you are trying to tell me.

What is the problem? What do you expect of the plugin?

Cheers!

**Comment by paveldostal** [comment]
Hi, if i make any change, if there is a change in blueprint or the changes in the files, files changes does not see with plugin, i have the latest version of the plugin.

**Comment by SRombauts** [comment]
Okay, now I understand. Can you give me more information please? What version of UE4 are you using, and which version of the plugin?

Can you check the Log files (in Project Saved/Logs/ subfolder) and see if there is anything special? Or post them here?

**Comment by paveldostal** [comment]
hi, i using ue 4.18 and i try it plugin version 2.6 and i try 2.7

**Comment by paveldostal** [comment]
hi, I attach a screenshot from my unreal project where I have very much modified files, but plugin menu checkout is disabled and I don't know why, please help, my version plugin is 2.6 and unreal engine 4.18

https://prnt.sc/iuawxz

**Comment by SRombauts** [comment]
Can you please post the associated log files?

**Comment by SRombauts** [comment]
Now I understand @paveldostal, with Git you cannot "checkout" files, you just have to "submit to Source Control"
