### ISSUE TITLE
Git plugin not working with `git worktree`

### ISSUE THREAD

**Issue by DJm00n** [SRombauts/UE4GitPlugin#76]
Plugin checks for `.git` directory but `git worktree` creating `.git` file instead (with actual gitdir path in it).
Check here must also consider `.git` file:
https://github.com/SRombauts/UE4GitPlugin/blob/047e7c8baebbc7c6d251b4c72a90321f18791394/Source/GitSourceControl/Private/GitSourceControlUtils.cpp#L340
Quickfix:
```
-               bFound = IFileManager::Get().DirectoryExists(*PathToGitSubdirectory);
+               bFound = IFileManager::Get().DirectoryExists(*PathToGitSubdirectory) || IFileManager::Get().FileExists(*PathToGitSubdirectory);
```

**Comment by SRombauts** [comment]
Thanks for reporting this, and for providing a quick fix!
