### ISSUE TITLE
Support git-fat

### ISSUE THREAD

**Issue by BenjaminDSmithy** [SRombauts/UE4GitPlugin#8]
git-fat appears to be a good alternative or even stepping stone to #1 (git-annex & git-media),

As there are less dependencies & there appears to be a more transparent workflow provided with the git-fat solution :+1:

git-fat Github Public Repo | https://github.com/jedbrown/git-fat

**Comment by SRombauts** [comment]
Hi, closing this, I will try to work on supporting Git LFS (issue #35)
