### ISSUE TITLE
ue4 "project could not be compiled try rebuilding from source manually" error after plugin import

### ISSUE THREAD

**Issue by nonamed46** [SRombauts/UE4GitPlugin#80]
Hey I saw your plugin and i instantly fell in love with it. So i installed it right away and for me alone it worked perfectly well.
We are joining the UE4 Summer Jam so i set up the project, put in the plugin and pushed it so my partner could use the project and the plugin as well but as soon as she starts the engine with the plugin in her project folder it crashes to 
"project could not be compiled try rebuilding from source manually" 
and something about it being compiled in a different version of the engine. [Update, see the images below]
Did we miss something?
She has the current standalone version of git on her pc, we also tried reinstalling it and i just can't find the issue. 
We are both using the prebuilt 4.20.1 Version which you get from the epic launcher.
The only difference on our PCs should be the Visual Studio Version (mine is at 2017, hers at 2015) but we are only using blueprints, she actually is only doing the art part for the game. Still maybe the engine can't compile the changes correctly because of that?
Thanks in advance!

**Comment by nonamed46** [comment]
![issue01](https://user-images.githubusercontent.com/33360469/44238318-7db50280-a1b4-11e8-9a7d-df8b7c60350b.PNG)
![issue02](https://user-images.githubusercontent.com/33360469/44238319-7e4d9900-a1b4-11e8-8f57-cbde07e2ebce.PNG)
i recreated the issue on my laptop to see the errors myself

**Comment by SRombauts** [comment]
Oh, sorry about that, I don't know for sure, but it looks a bit like a release problem if the Git plugin:
1. First of all, you might want to try using the version of the git plugin that I maintain directly in Unreal Engine 4.20 instead of using this development version of the git plugin (if it suits your needs, ie without Git LFS 2 locks) 
2. Are you using the latest version of this git plugin, that is, the latest commit/release for 4.20? If so, it might be an issue on my side... 
3. Can you provide the logs from your project Saved/Logs subfolder? Not sure there is anything in it though...

**Comment by nonamed46** [comment]
Hi, i'm really sorry it took me so long to come back to you.

(our standalone git is on the newest version, just as a reminder)
We were using the plugin version provided under the "code" tab.

Firstly I set up a fresh repository on github (https://github.com/nonamed46/GitPluginTest1000.git if you want to see for yourself) with the ue4 gitignore template.
I cloned it with Sourcetree and created a new UE4 Project inside the folder.
Then I created a new Plugins folder and moved your Plugin inside that.
In UE4 I was able to connect to the source control and perform a small commit over 2 files(The .uproject and the Startup Map). Since i wanted the full Project in the repository i pushed all not yet committed (AND not ignored!) files using sourcetree.
Once i pull that on my laptop i get the error from the previous post.
Might it be an issue with the gitignore preset, so might there be some missing files maybe?
I provided the logfile of my Laptop as an attachement.

Again, sorry for the long wait and thank you for your quick response. Also sorry if it's just a very dumb error on my side, i'm not very experienced in this sector yet :D

[GitTest.log](https://github.com/SRombauts/UE4GitPlugin/files/2343286/GitTest.log)

**Comment by ArtyMcLabin** [comment]
i had this issue after migrating to 4.20 from 4.18 **solved by** deleting the older version completely (like really really completely. nuking the folder) and replacing it with the most recent one solved the issue for me. (tried to overwrite before that and it didn't help)

**Comment by KristofMorva** [comment]
@nonamed46 you have a problem with your VS settings:
> WARNING: Visual Studio 2017 is installed, but is missing the C++ toolchain. Please verify that the "VC++ 2017 toolset" component is selected in the Visual Studio 2017 installation options.

You should select `Visual Studio 2017` in the editor settings, and install VS2017 components as instructed in the Documentation.

**Comment by TotallyCoded** [comment]
Make sure you are copying the whole plugin folder and not just the .uplugin. I got that same error when only copying the .uplugin but after copying the whole folder it seems to have worked.

**Comment by nonamed46** [comment]
wow this was long ago^^
I think the issue was that we didn't know how to install the plugin correctly.
By excluding the "plugins" directory completely from our repository we managed to get it running.
It also might have been trouble with github's ue4 gitignore preset.
