### ISSUE TITLE
Git Plugin doesn't work with UE 4.21.0

### ISSUE THREAD

**Issue by JuKu** [SRombauts/UE4GitPlugin#85]
The current version of the git plugin doesn't any longer work with Unreal Engine 4.21.0 .
Can you please fix this?

**Comment by SRombauts** [comment]
True, you need to rebuild it.
I'll do that asap

**Comment by SRombauts** [comment]
Hi @JuKu, thanks to you I have rebuild and release a new version of my plugin for UE4.21 https://github.com/SRombauts/UE4GitPlugin/releases/tag/2.10-beta

Thank you :)
