### ISSUE TITLE
It didn't Commit or Push C++ Classes

### ISSUE THREAD

**Issue by bbagwang** [SRombauts/UE4GitPlugin#89]
I try to use this really nice plugin for my project but It doesn't commit or push any C++ Classes
it only works on first Initial push.
I think I do something wrong because initially, it pushes the C++ Classes.
can you help me?
I made a Actor class named "Item" but it didn't pushed

my test repo is here : https://github.com/bbagwang/TEST

**Comment by SRombauts** [comment]
This is not an issue, but simply the way Unreal Editor works ; it does not know about source code

**Comment by SRombauts** [comment]
Sorry, but this is the kind of things only Epic Games can change

**Comment by bbagwang** [comment]
Okay, thank you :)
