### ISSUE TITLE
Global namespace 'GitSourceControl' used already

### ISSUE THREAD

**Issue by patrickShaikh** [SRombauts/UE4GitPlugin#94]
Hey,

I'm working with a source build of the unreal engine and trying to install this plugin using this steps:

https://answers.unrealengine.com/questions/518976/how-to-install-plugins-in-sourcebuild.html

When executing the GenerateProjectFiles..bat it shows me this error 

![grafik](https://user-images.githubusercontent.com/40237073/55447627-c3e49800-55c4-11e9-8de4-a7a8bded82ce.png)

I know it's in german but it basically says, that the namespace 'GitSourceControl' is already used and it cannot compile becouse of that.

**Comment by MekuCube** [comment]
We didn't have this issue when we pulled and built the plugin, but we also built directly in Visual Studio 2019. Maybe that makes a difference?

**Comment by SRombauts** [comment]
Sorry, you can't build this Git plugin v2 in the UnrealEngine Plugins directory because it already contains my Git plugin v1 (Plugins/Developer/GitSourceControl): well, you can delete this v1 folder, and put the v2 in place.

The usual and recommended way of building the v2 plugin is to put it directly in your project's on Plugins folder, instead of in the UnrealEngine one

Cheers!

**Comment by OdinVex** [comment]
This most definitely needs to be added to the README...

**Comment by SRombauts** [comment]
Hi!

It is definitely writen quite clearly in the README.
Do you have any suggestion to improve the docs?

```
Install this Git Plugin (dev) into your Game Project
Unreal Engine comes with a stable version of this plugin, so no need to install it.

This alternate "Git development plugin" needs to be installed into a subfolder or your Game Project "Plugins" directory (that is, you cannot install it into the Engine Plugins directory):

<YourGameProject>/Plugins
You will obviously only be able to use the plugin within this project.
```

**Comment by OdinVex** [comment]
> Hi!
> ...

I had to remove the Engine/Plugin/Developer/GitSourceControl for it to compile on Linux. Yes, even as a Plugin for Project-only.
